### PR TITLE
Compose

### PR DESCRIPTION
**Pull request by asher-pembroke**
Trying out `docker compose` a la #79

I seem to be getting more stable runs on my mac when switching to this.

```console
docker --version 
Docker version 20.10.8, build 3967b7d
```

We should probably point to the install instructions for compose [here](https://docs.docker.com/compose/install/).

### CODE REVIEW

**Comment by rsafier** [comment]
need to check but looks like linux doesn't have access to docker compose command at least my docker version is same as my Mac, but doesn't have compose function embedded. might need to roll this back or have switch for platform

**Comment by rsafier** [comment]
oh does look like I can get that functionality by following instructions https://github.com/docker/compose#linux

**Comment by asher-pembroke** [comment]
We could add a check to see if `compose` exists and fall back to `docker-compose` if it doesn't. let me know what you think

**Comment by rsafier** [comment]
might not be a bad idea until it is packaged a little more conveniently on ubuntu. and/or add explicit link to manual install, as it is smoother long-term.

**Pull request merged**
