### PR TITLE
volumes: add persistent data directories

### PR DESCRIPTION
**Pull request by RandyMcMillan**
volumes: add persistent data directories

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
We can add example/default configs to the data directories.

**Comment by RandyMcMillan** [comment]
the docker-compose references relative paths that don't exist by default.
This causes an error in docker when starting up.

https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker/blob/992a0e887d984440a91f074d40be2f3b0f52226c/docker-compose.yaml#L26

This change addresses the issue.

**Comment by rsafier** [comment]
> the docker-compose references relative paths that don't exist by default.
> This causes an error in docker when starting up.
> 
> https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker/blob/992a0e887d984440a91f074d40be2f3b0f52226c/docker-compose.yaml#L26
> 
> This change addresses the issue.

if we could improve this so we have a purge of some sort. currently have the install and uninstall scripts doing this

**Comment by rsafier** [comment]
the issue with volumes stuff is if end user is not running as root they don't have access to all the files in the volumes as they tend to be under root how things are wired right now

**Comment by asherp** [comment]
> the issue with volumes stuff is if end user is not running as root they don't have access to all the files in the volumes as they tend to be under root how things are wired right now

I am not seeing this issue on my mac. I created a non-admin account and followed all the install steps from the README.md after pulling this branch. The only thing I needed admin permission for was the initial install of docker. Am I testing this right?

**Comment by RandyMcMillan** [comment]
ok - I didnt realize it was a file permissions issue - there is a fix for this - i will take another look.

**Comment by rsafier** [comment]
> > the issue with volumes stuff is if end user is not running as root they don't have access to all the files in the volumes as they tend to be under root how things are wired right now
> 
> I am not seeing this issue on my mac. I created a non-admin account and followed all the install steps from the README.md after pulling this branch. The only thing I needed admin permission for was the initial install of docker. Am I testing this right?

so after you make lnd wallet go look into the chain or other directory they are root, at least on normal linux box

**Comment by rsafier** [comment]
the defaults also are already in the docker containers so having a hard time understanding why we would want to do this, perhaps a CH voice chat would be easier to discuss and make me understand advantages

**Comment by asherp** [comment]
#7 may help resolve linux permissions issue

**Pull request closed without merging**
