### PR TITLE
Add lndg

### PR DESCRIPTION
**Pull request by cryptosharks131**

### CODE REVIEW

**Comment by asher-pembroke** [comment]
port `8888` conflicts with the notebook service.

**Comment by RandyMcMillan** [comment]
Error on MacOS Docker Desktop Version 3.5.2 (3.5.2.18)


Screen Shot 2021-09-30 at 7 19 08 PM

**Comment by cryptosharks131** [comment]
This should be fixed now!

**Comment by RandyMcMillan** [comment]
Got it working on MacOS x86_64

Screen Shot 2021-09-30 at 8 02 20 PM

**Comment by RandyMcMillan** [comment]
Working on Arm64 MacOS as well...

Screen Shot 2021-09-30 at 8 11 22 PM

**Comment by RandyMcMillan** [comment]
Here is the change:

https://github.com/RandyMcMillan/plebnet-playground-docker/commit/00645b17e1bd455d5ac481d03a3b3c6ff6ee4095

**Comment by RandyMcMillan** [comment]
Update the change: land only need read access:

https://github.com/RandyMcMillan/plebnet-playground-docker/commit/2ffef5fa7cb7bddbc6e7155d62d6decacfde95cc

**Comment by cryptosharks131** [comment]
The link in the change you proposed is not quite right as the site lives at `/lndg` inside the container but it allows the site to work because it just runs the db file internal to the container instead since there is no longer a path conflict.

Can you verify that you have `git pull` the last update that changed `install.sh` and properly initializes the file before running the containers?

**Comment by RandyMcMillan** [comment]
I tested ./getcoins.py and the data was detected and displayed....

Screen Shot 2021-09-30 at 8 45 07 PM
Screen Shot 2021-09-30 at 8 45 28 PM

I could be missing something but...

commit 2ffef5fa7 is working...

**Comment by cryptosharks131** [comment]
Commit should work because the file is running inside the container now I believe. Do you see the db file locally at your `${oc.env:PWD}/volumes/lndg_datadir/db.sqlite3` path?

**Comment by RandyMcMillan** [comment]
This is what it looks like...

Screen Shot 2021-09-30 at 8 52 46 PM

**Comment by RandyMcMillan** [comment]
Let me rebase and check again...

**Comment by RandyMcMillan** [comment]
Commit ea9f3dc9a

After running getcoins.py the balance doesn't show up...

**Comment by cryptosharks131** [comment]
> Commit [ea9f3dc](https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker/commit/ea9f3dc9af1f89388f3c4b77f6f6d4ff9757abd9)
> 
> After running getcoins.py the balance doesn't show up...

This is strange because balances are a direct call to lnd and not related to the db file.

I was able to spin up a new container and use `getcoins.py` to add funds and open a channel.

**Comment by RandyMcMillan** [comment]
Confirm indg that commit ea9f3dc9a
Works on macOS x86_64 and Arn64

**Comment by RandyMcMillan** [comment]
ignore comment  https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker/pull/41#issuecomment-931814867

**Comment by RandyMcMillan** [comment]
PS: @cryptosharks131 - I am going to retool ```make install``` and ```make install nocache=true``` so there is an option to restart the stack with persistent data using ```make```.

**Comment by RandyMcMillan** [comment]
tACK ea9f3dc9af1f89388f3c4b77f6f6d4ff9757abd9
👍🏽

**Pull request merged**
